'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrgBraCal
    
    '''<summary>
    '''lblDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''frmOrgCal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmOrgCal As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txbDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DdlH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlH As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlAPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlAPM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlSl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlSl As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlSc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlSc As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txaDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txaDes As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''calOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calOrg As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''BtnCal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCal As Global.System.Web.UI.WebControls.Button
End Class
