
/****** Object:  Database [dbads]    Script Date: 2018/07/08 05:58:54 PM ******/
CREATE DATABASE [dbads]
GO

ALTER DATABASE [dbads] SET COMPATIBILITY_LEVEL = 110
GO

ALTER DATABASE [dbads] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbads] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbads] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbads] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbads] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbads] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [dbads] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [dbads] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbads] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbads] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbads] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbads] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbads] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbads] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbads] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbads] SET  ENABLE_BROKER 
GO

ALTER DATABASE [dbads] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbads] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbads] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbads] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbads] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbads] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbads] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbads] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbads] SET  MULTI_USER 
GO

ALTER DATABASE [dbads] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbads] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbads] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbads] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbads] SET  READ_WRITE 
GO
