'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Registration
    
    '''<summary>
    '''frmReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmReg As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txbInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbInfo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''usrName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''usrSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrSurname As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''usrEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrEmail As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''lblVemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVemail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPwd As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''usrPasswd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrPasswd As Global.System.Web.UI.HtmlControls.HtmlInputPassword
    
    '''<summary>
    '''lblVpasswd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVpasswd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rdbList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbList As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lblRlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRlist As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRegister As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFed As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cldInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cldInfo As Global.System.Web.UI.WebControls.Calendar
End Class
