'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Login
    
    '''<summary>
    '''frmLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmLog As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txbInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbInfo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''usrEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrEmail As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''usrPasswd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrPasswd As Global.System.Web.UI.HtmlControls.HtmlInputPassword
    
    '''<summary>
    '''BtnLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLogin As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFed As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''calInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calInfo As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''placeHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents placeHolder As Global.System.Web.UI.WebControls.PlaceHolder
End Class
